<<<<<<< HEAD
main: com.hofill.mastermind.main
version: 1.0
name: Mastermind
=======
main: com.hofill.mastermindTest.main
version: 1.0
name: Test
>>>>>>> fb51699b0bd167586e616229ab1feb618c58822b
api-version: 1.13

commands:
  setupgame:
    description: Creates the Mastermind game
    usage: /setupgame
  removefromstate:
    description: Removes player from the game creation state -Use with caution-
    usage: /removefromstate <name>
  mastermind:
    description: Main command for mastermind.
    usage: /mastermind <option> <option>