main: com.hofill.mastermind.main
version: 1.0
name: Mastermind
api-version: 1.13

commands:
  setupgame:
    description: Creates the Mastermind game
    usage: /setupgame
  removefromstate:
    description: Removes player from the game creation state -Use with caution-
    usage: /removefromstate <name>
  mastermind:
    description: Main command for mastermind.
    usage: /mastermind <option> <option>
