main: com.hofill.mastermindTest.main
version: 1.0
name: Test

commands:
  setupgame:
    description: Creates the Mastermind game
    usage: /setupgame
  removefromstate:
    description: Removes player from the game creation state -Use with caution-
    usage: /removefromstate <name>